### PR TITLE
Propagate rename of collection to calendar_name introduced in 1a262b4

### LINKED ISSUE #1235: Error while saving an external edit of an event from ikhal
I am trying to edit an event by pressing 'meta_E' (external edit). But when I try to save the edit (I changed the time), khal crashes with the following python traceback:

```
 File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 1364, in start_pane
    loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 287, in run
    self._run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 385, in _run
    self.event_loop.run()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 790, in run
    self._loop()
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 827, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 416, in <lambda>
    wrapper = lambda: self.parse_input(
  File "/usr/lib/python3.10/site-packages/urwid/raw_display.py", line 515, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 412, in _update
    self.process_input(keys)
  File "/usr/lib/python3.10/site-packages/urwid/main_loop.py", line 513, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.10/site-packages/urwid/wimp.py", line 651, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 1135, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 1124, in keypress
    return super().keypress(size, key)
  File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/base.py", line 114, in keypress
    return super().keypress(size, key)
  File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/widgets.py", line 313, in keypress
    key = super().keypress(size, key)
  File "/usr/lib/python3.10/site-packages/urwid/container.py", line 2316, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 930, in keypress
    self.edit(self.focus_event.event, external_edit=True)
  File "/home/myuser/.local/lib/python3.10/site-packages/khal/ui/__init__.py", line 749, in edit
    new_event = self.pane.collection.create_event_from_ics(
TypeError: CalendarCollection.create_event_from_ics() got an unexpected keyword argument 'collection'

 
```

### PR DESCRIPTION
**Pull request by prataffel**
This should fix #1235 by propagating the rename of `collection` to `calendar_name` in `Calendar.Collection.create_event_from_ics`, introduced in 1a262b4.

### CODE REVIEW

**Comment by WhyNotHugo** [comment]
This is correct, thanks!
