### ISSUE TITLE
Compatibility with icalendar >= 4.0.3

### ISSUE THREAD

**Issue by lucc** [pimutils/khal#823]
This is for python 3.7.1 (installed from the arch repos) and khal 0.9.7.dev121+g1bc431f (same for khal 0.9.10 from the arch repos)

I created an event like this `khal new -g uni 10.02.2019 23:00 23:58 -g uni Rust project submission`. Now If I select the event in ikhal it crashes with this exception: 
```
$ PYTHONPATH=. python -m khal interactive
Traceback (most recent call last):
  File "/home/luc/vcs/khal/khal/ui/__init__.py", line 1346, in start_pane
    loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 286, in run
    self._run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 384, in _run
    self.event_loop.run()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 788, in run
    self._loop()
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 825, in _loop
    self._watch_files[fd]()
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 404, in <lambda>
    event_loop, callback, self.get_available_raw_input())
  File "/usr/lib/python3.7/site-packages/urwid/raw_display.py", line 502, in parse_input
    callback(processed, processed_codes)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 411, in _update
    self.process_input(keys)
  File "/usr/lib/python3.7/site-packages/urwid/main_loop.py", line 511, in process_input
    k = self._topmost_widget.keypress(self.screen_size, k)
  File "/usr/lib/python3.7/site-packages/urwid/wimp.py", line 648, in keypress
    return self._current_widget.keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 1131, in keypress
    return self.body.keypress( (maxcol, remaining), key )
  File "/home/luc/vcs/khal/khal/ui/__init__.py", line 1108, in keypress
    return super().keypress(size, key)
  File "/home/luc/vcs/khal/khal/ui/base.py", line 114, in keypress
    return super().keypress(size, key)
  File "/home/luc/vcs/khal/khal/ui/widgets.py", line 308, in keypress
    key = super(NextMixin, self).keypress(size, key)
  File "/usr/lib/python3.7/site-packages/urwid/container.py", line 2271, in keypress
    key = w.keypress((mc,) + size[1:], key)
  File "/home/luc/vcs/khal/khal/ui/__init__.py", line 927, in keypress
    self.view(self.focus_event.event)
  File "/home/luc/vcs/khal/khal/ui/__init__.py", line 642, in view
    (EventDisplay(self.pane._conf, event, collection=self.pane.collection),
  File "/home/luc/vcs/khal/khal/ui/__init__.py", line 956, in __init__
    lines.append(urwid.Text('Categories: ' + event.categories))
TypeError: can only concatenate str (not "vCategory") to str
```
If I try the edit the category non interactively I get this exception (I pressed enter on the second prompt):
```
% khal edit rust project
10.02. 23:00-10.02. 23:58 Rust project submission
Edit?  [n]o  [q]uit  [s]ummary  [d]escription  da[t]etime range  re[p]eat  [l]ocation  [c]ategories  [a]larm  [D]elete: c
categories (or "None") [<icalendar.prop.vCategory object at 0x7f063ee684a8>]: 
Traceback (most recent call last):
  File "/usr/bin/khal", line 5, in <module>
    main_khal()
  File "/usr/lib/python3.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.7/site-packages/khal/cli.py", line 587, in edit
    conf=ctx.obj['conf']
  File "/usr/lib/python3.7/site-packages/khal/controllers.py", line 517, in edit
    if not edit_event(event, collection, locale, allow_quit=True, width=term_width):
  File "/usr/lib/python3.7/site-packages/khal/controllers.py", line 492, in edit_event
    getattr(event, "update_" + attr)(value)
  File "/usr/lib/python3.7/site-packages/khal/khalendar/event.py", line 415, in update_categories
    if categories.strip():
AttributeError: 'vCategory' object has no attribute 'strip'
```

**Comment by geier** [comment]
Thank you for the report, I'll have a look at this.

**Comment by geier** [comment]
I can't actually reproduce this on my machine. Can you paste the .ics file that gets created?

**Comment by geier** [comment]
ah, this breakage is due to an icalendar update, I can reproduce with icalendar 4.0.3 (but it still worked with 4.0.2). I will change the headline accordingly and try to get this fixed ASAP.

**Comment by serussell** [comment]
Confirmed, and for any Arch users looking for a fix: assuming it was working prior to the package upgrade and you haven't cleaned your cache:

```
pacman -U /var/cache/pacman/pkg/python-icalendar-<TAB>
```

and pick the latest version that isn't 4.0.3-something.

**Comment by serussell** [comment]
Brand new laptop, brand new arch... ran into this problem again, only this time I didn't have a cached version of an earlier python-icalendar.  Here's a fix for others in the same boat:

```
pacman -U https://archive.archlinux.org/packages/p/python-icalendar/python-icalendar-4.0.2-2-any.pkg.tar.xz
```

**Comment by geier** [comment]
Should be fixed with https://github.com/pimutils/khal/pull/850, I'll make a new release ASAP
