### ISSUE TITLE
Test `test_popup()` on  `test_editor.py` failed with urwid v. 2.1.0

### ISSUE THREAD

**Issue by ephase** [pimutils/khal#903]
With the latest urwid version, `test_popup()` failed with the message :

```
self = <[AttributeError("'CalendarWidget' object has no attribute '_wrapped_widget'") raised in repr()] CalendarWidget object at 0x7f043271eb50>
```
When I downgrade the version of urwid to 2.0.1 on my venv, this particular test file work like a charm.

**Comment by ephase** [comment]
I found the commit that introduced this behavior on `urwid` code with git bisect : https://github.com/urwid/urwid/commit/018509d1b6af0cba9a76b2eea5648e63b46e5fd3

**Comment by d7415** [comment]
I've found a dirty workaround. I'll see if I can figure out what's actually going on.

**Comment by ephase** [comment]
I though to change the test by using render()method but i don't had time to test it these days.
